---
name: Build, lint, test
run-name: Test JS CLI (started by @${{ github.triggering_actor }})

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build_test_lint:
    name: Build, test, and lint
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
      - name: Install
        run: yarn --network-timeout 180000
      - name: Typecheck
        run: yarn run test:types
      - name: Build
        run: yarn run build
      - name: Add TSS server host mappings
        run: |
          echo "127.0.0.1 alice-tss-server bob-tss-server charlie-tss-server dave-tss-server" | sudo tee -a /etc/hosts
      - name: Test
        run: yarn run test
